
version: "3.9"
services:
  app:
    build: .
    ports:
      - "5572:5572"
      - "5573:5573"
      - "53682:53682"
    volumes:
      - /volume1/docker/rclone/config:/config
      - /volume3/photo:/data
    user: "0:0"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
